version: "1.0"
indexPath: ./index
indexMode: INDEX_SPARQL_ENDPOINT
sparqlEndpoint: https://dbpedia.org/sparql
cleanIndex: true
cacheSize: 1000000
commitInterval: 100
indexFields:
  - fieldName: label
    documentVariable: city
    query: >
      SELECT ?city ?label WHERE {
        {
          ?city a <http://dbpedia.org/ontology/City> .
          ?city <http://www.w3.org/2000/01/rdf-schema#label> ?label .
          FILTER (LANG(?label) = "en").
        }
      } LIMIT 10000
  - fieldName: birthPlace
    documentVariable: person
    type: stored
    query: >
      SELECT ?person ?birthPlace WHERE {
        {
          ?resource a <http://dbpedia.org/ontology/Person> .
          ?resource <http://dbpedia.org/ontology/birthPlace> ?birthPlace .
        }
      } LIMIT 10000