version: "1.0"
indexPath: ./index
exactMatchBoost: 10
prefixMatchBoost: 5
fuzzyMatchBoost: 2
fuzzyEditDistance: 2
fuzzyPrefixLength: 2
maxResults: 100
format: JSON
minScore: 0.1
queryFields:
  - fieldName: birthPlace
    weight: 10
    tokenize: true
  - fieldName: label
    weight: 10
    highlight: true
    tokenize: true
    queryByDefault: true