version: "1.0"
indexPath: ./index
exactMatchBoost: 10
prefixMatchBoost: 5
fuzzyMatchBoost: 2
fuzzyEditDistance: 2
fuzzyPrefixLength: 2
maxResults: 100
format: JSON
minRelevanceScore: 0.1
queryFields:
  - fieldName: label
    weight: 10
    highlight: true
    tokenize: true
    queryByDefault: true
  - fieldName: resource
    weight: 10
    exact: true
    tokenize: false
    queryByDefault: true
  - fieldName: annotation
    weight: 10
    exact: true
    tokenize: false
    queryByDefault: true
  - fieldName: oeoNumber
    weight: 10
    highlight: true
    exact: true
    queryByDefault: true
  - fieldName: classId
    exact: true
    weight: 10
    highlight: true
    queryByDefault: true